"""2

Revision ID: 81f80236845f
Revises: a7edf35e3d10
Create Date: 2022-10-29 21:27:40.032718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f80236845f'
down_revision = 'a7edf35e3d10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'advertisement', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisement', type_='foreignkey')
    op.drop_column('advertisement', 'author_id')
    # ### end Alembic commands ###
