"""4

Revision ID: f83e412a0903
Revises: f61d222ea42a
Create Date: 2022-10-29 21:41:52.066017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f83e412a0903'
down_revision = 'f61d222ea42a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisement', 'type_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('advertisement', 'place_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('advertisement', 'author_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user', 'place_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'place_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('advertisement', 'author_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('advertisement', 'place_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('advertisement', 'type_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
